### ISSUE TITLE
Can't see the lightbulb, get an error after installation

### ISSUE THREAD

**Issue by naoric** [tusaeff/vscode-typescript-destructure-plugin#7]
Hi, thanks for this super helpful extension!  (especially with a keyboard shortcut).

For some reason I can't see the lightbulb when the cursor is over an object (props) or when selecting the variable. 

After restart I immediately get this error:

```
ERR <semantic> TypeScript Server Error (4.0.2)
Cannot read property 'kind' of undefined
TypeError: Cannot read property 'kind' of undefined
    at Object.canBeDestructured (/Users/\.../.vscode/extensions/tusaeff.vscode-typescript-destructure-plugin-0.0.10/node_modules/typescript-destructure-plugin/dist/plugin.js:155526:67)
    at DestructureInPlace.canBeApplied (/Users/\.../.vscode/extensions/tusaeff.vscode-typescript-destructure-plugin-0.0.10/node_modules/typescript-destructure-plugin/dist/plugin.js:155067:21)
    at /Users/\.../.vscode/extensions/tusaeff.vscode-typescript-destructure-plugin-0.0.10/node_modules/typescript-destructure-plugin/dist/plugin.js:154982:40
    at Array.filter (<anonymous>)
    at Object.getApplicableRefactors (/Users/\.../.vscode/extensions/tusaeff.vscode-typescript-destructure-plugin-0.0.10/node_modules/typescript-destructure-plugin/dist/plugin.js:154982:10)
    at Object.proxy.getApplicableRefactors (/Users/\.../.vscode/extensions/tusaeff.vscode-typescript-destructure-plugin-0.0.10/node_modules/typescript-destructure-plugin/dist/plugin.js:155023:52)
    at IOSession.Session.getApplicableRefactors (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154604:53)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:153349:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154953:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154944:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154953:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154977:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:157193:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23): Error: <semantic> TypeScript Server Error (4.0.2)
Cannot read property 'kind' of undefined
TypeError: Cannot read property 'kind' of undefined
    at Object.canBeDestructured (/Users/\.../.vscode/extensions/tusaeff.vscode-typescript-destructure-plugin-0.0.10/node_modules/typescript-destructure-plugin/dist/plugin.js:155526:67)
    at DestructureInPlace.canBeApplied (/Users/\.../.vscode/extensions/tusaeff.vscode-typescript-destructure-plugin-0.0.10/node_modules/typescript-destructure-plugin/dist/plugin.js:155067:21)
    at /Users/\.../.vscode/extensions/tusaeff.vscode-typescript-destructure-plugin-0.0.10/node_modules/typescript-destructure-plugin/dist/plugin.js:154982:40
    at Array.filter (<anonymous>)
    at Object.getApplicableRefactors (/Users/\.../.vscode/extensions/tusaeff.vscode-typescript-destructure-plugin-0.0.10/node_modules/typescript-destructure-plugin/dist/plugin.js:154982:10)
    at Object.proxy.getApplicableRefactors (/Users/\.../.vscode/extensions/tusaeff.vscode-typescript-destructure-plugin-0.0.10/node_modules/typescript-destructure-plugin/dist/plugin.js:155023:52)
    at IOSession.Session.getApplicableRefactors (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154604:53)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:153349:61)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154953:88
    at IOSession.Session.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154944:28)
    at IOSession.Session.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154953:33)
    at IOSession.Session.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:154977:35)
    at Interface.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:157193:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
  at Function.create (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:76465)
  at h.dispatchResponse (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:70340)
  at h.dispatchMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:69199)
  at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension.js:1:68709
```

**Comment by KilianKilmister** [comment]
Same here, I just discovered a similar issue with a different extention. Turned out it threw a syntax error when i used typescript@4.0 Named Touples because the extention used an outdated parser. Similarly here, the extention is using typescript@3.9.5. Now that i'm seing someone with the same error who also uses typescrit@4+ I'm pretty sure that's the reason for this error.


from this extentions `package.json`
```
{
  "dependencies": {
    "typescript": "^3.9.5"
  },
}
```

**Comment by Lonli-Lokli** [comment]
Same for me, unfortunately

**Comment by amaleky** [comment]
Im using typescript@4.5.4 and plugin not working at all

**Comment by sdivakarrajesh** [comment]
I do get a lightbulb - but it kinda looks different from the ones shown in the example though. Something changed in the vscode side? i don't see this snippet showing at all when the variable that can be destrucutured is highlighted
